#- name: Configure dune
#  hosts: dune
#  roles:
#    - dhcp-server

- name: Configure katana
  hosts: katana
  roles:

- name: Configure wylie
  hosts: wylie
  roles:
    - monitorix
    - nginx
    - system

