- name: Configure all servers
  hosts:
    - dune
    - fuji
    - wylie
  roles:
    - system
#    - network
#    - ssh-server
#    - tools
    
- name: Configure dune
  hosts: dune
  roles:
    - dhcp-server

- name: Configure fuji
  hosts: fuji
  roles:

- name: Configure wylie
  hosts: wylie
  roles:
    - monitorix
    - nginx

