- name: Configure dune
  hosts: dune
  roles:
#    - dhcp-server

- name: Configure katana
  hosts: katana
  roles:
    - tools
    - system

- name: Configure wylie
  hosts: wylie
  roles:
    - monitorix
    - nginx
    - spy
    - system

