---
- name: interfaces
  copy:
    src: roles/network/files/interfaces
    dest: /etc/network/interfaces
    backup: yes
  when: ansible_facts['hostname'] == "dune"

- name: default DNS
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 8.8.8.8"
    create: yes

