---
- name: interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes

- name: default DNS
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 8.8.8.8"
    create: yes

