
- name: Install tools packages
  become: yes
  ansible.builtin.package:
    name:     "{{item}}"
    state:    present
  loop:
    - locate
    - gcc
    - git
    - gnome-screenshot
    - google-chrome-stable
    - make
    - ruby
    - ruby-devel
    - tree

- name: Install dev tools
  become: yes
  ansible.builtin.copy:
    src:   "{{item}}"
    dest:  "/bin/{{item}}"
    owner: root
    group: root
    mode:  0755
  loop:
    - build
    - clean

