
- name: Install package
  become: yes
  ansible.builtin.package:
    name:     monitorix
    state:    present

- name: Install service
  become: yes
  ansible.builtin.copy:
    src:   monitorix
    dest:  /usr/bin/monitorix
    owner: root
    group: root
    mode:  0755
  notify: restart Monitorix

- name: Configure service
  become: yes
  ansible.builtin.copy:
    src:   monitorix.conf
    dest:  /etc/monitorix/monitorix.conf
    owner: root
    group: root
    mode:  0644
  notify: restart Monitorix

- name: Install cgi script
  become: yes
  ansible.builtin.copy:
    src:   monitorix.cgi 
    dest:  /var/lib/monitorix/www/cgi/monitorix.cgi
    owner: root
    group: root
    mode:  0755
  notify: restart Monitorix

- name: Enable service
  become: yes
  ansible.builtin.service:
    name:     monitorix
    enabled:  true
    state:    started

- name: Install css
  become: yes
  ansible.builtin.copy:
    src:   "{{item}}.css"
    dest:  "/var/lib/monitorix/www/css/{{item}}.css"
    owner: root
    group: root
    mode:  0644
  loop:
    - black
    - white
  notify: restart Monitorix

- name: Install index.html
  become: yes
  ansible.builtin.copy:
    src:   index.html
    dest:  /var/lib/monitorix/www/index.html
    owner: root
    group: root
    mode:  0644
  notify: restart Monitorix

