
- name: Install package
  become: yes
  ansible.builtin.package:
    name:     monitorix
    state:    present

- name: Enable service
  become: yes
  ansible.builtin.service:
    name:     monitorix
    enabled:  true
    state:    started

- name: Configure service
  become: yes
  ansible.builtin.copy:
    src:   monitorix.conf
    dest:  /etc/monitorix/monitorix.conf
    owner: root
    group: root
    mode:  0644
  notify: restart Monitorix

- name: Install cgi script
  become: yes
  ansible.builtin.copy:
    src:   monitorix.cgi 
    dest:  /var/lib/monitorix/www/cgi/monitorix.cgi
    owner: root
    group: root
    mode:  0755
  notify: restart Monitorix

- name: Install home page
  become: yes
  ansible.builtin.copy:
    src:   home.html
    dest:  /var/lib/monitorix/www/home.html
    owner: root
    group: root
    mode:  0644
  notify: restart Monitorix

