---

- name: allow root access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin +"
    line: "PermitRootLogin yes"
  notify:
    - restart sshd

- name: disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication +"
    line: "PasswordAuthentication no"
  notify:
    - restart sshd

- name: disable empty password 
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitEmptyPasswords +"
    line: "PermitEmptyPasswords no"
  notify:
    - restart sshd

- name: allow only known users
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AllowUsers .*"
    line: "AllowUsers root pba"
  notify:
    - restart sshd

- name: create user's .ssh directory
  file:
    path:  /home/{{item}}/.ssh
    state: directory
  loop:
    - pba

- name: update user's .ssh/authorized_keys
  copy:
    src:  authorized_keys 
    dest: /home/{{item}}/.ssh/authorized_keys
  loop:
    - pba

